apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "emqx.fullname" . }}
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "emqx.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "emqx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "emqx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: emqx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: EMQX_NODE_NAME
          value: "emqx@$(POD_IP)"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EMQX_CLUSTER__DISCOVERY_STRATEGY
          value: {{ .Values.emqx.clustering.discovery_strategy }}
        {{- if eq .Values.emqx.clustering.discovery_strategy "k8s" }}
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: {{ include "emqx.fullname" . }}
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: {{ .Values.namespace }}
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: {{ .Values.emqx.clustering.k8s.address_type }}
        {{- end }}
        - name: EMQX_DASHBOARD__DEFAULT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "emqx.fullname" . }}-auth
              key: admin-username
        - name: EMQX_DASHBOARD__DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "emqx.fullname" . }}-auth
              key: admin-password
        - name: EMQX_NODE__COOKIE
          valueFrom:
            secretKeyRef:
              name: {{ include "emqx.fullname" . }}-auth
              key: erlang-cookie
        ports:
        - name: mqtt
          containerPort: {{ .Values.service.ports.mqtt }}
          protocol: TCP
        - name: mqttssl
          containerPort: {{ .Values.service.ports.mqttssl }}
          protocol: TCP
        - name: ws
          containerPort: {{ .Values.service.ports.ws }}
          protocol: TCP
        - name: wss
          containerPort: {{ .Values.service.ports.wss }}
          protocol: TCP
        - name: dashboard
          containerPort: {{ .Values.service.ports.dashboard }}
          protocol: TCP
        - name: erlang-dist
          containerPort: 4370
          protocol: TCP
        - name: cluster-rpc
          containerPort: 5370
          protocol: TCP
        {{- if .Values.healthcheck.enabled }}
        livenessProbe:
          httpGet:
            path: /status
            port: dashboard
          initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
          failureThreshold: {{ .Values.healthcheck.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /status
            port: dashboard
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: emqx-data
          mountPath: /opt/emqx/data
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: emqx-data
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}

---
{{- define "emqx.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{- define "emqx.labels" -}}
helm.sh/chart: {{ include "emqx.chart" . }}
{{ include "emqx.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{- define "emqx.selectorLabels" -}}
app.kubernetes.io/name: {{ include "emqx.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- define "emqx.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "emqx.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}