apiVersion: v1
kind: Service
metadata:
  name: {{ include "emqx.fullname" . }}
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: mqtt
    port: {{ .Values.service.ports.mqtt }}
    targetPort: mqtt
    protocol: TCP
  - name: mqttssl
    port: {{ .Values.service.ports.mqttssl }}
    targetPort: mqttssl
    protocol: TCP
  - name: ws
    port: {{ .Values.service.ports.ws }}
    targetPort: ws
    protocol: TCP
  - name: wss
    port: {{ .Values.service.ports.wss }}
    targetPort: wss
    protocol: TCP
  - name: dashboard
    port: {{ .Values.service.ports.dashboard }}
    targetPort: dashboard
    protocol: TCP
  - name: erlang-dist
    port: 4370
    targetPort: erlang-dist
    protocol: TCP
  - name: cluster-rpc
    port: 5370
    targetPort: cluster-rpc
    protocol: TCP
  selector:
    {{- include "emqx.selectorLabels" . | nindent 4 }}
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "emqx.fullname" . }}-lb
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - name: mqtt
    port: {{ .Values.service.ports.mqtt }}
    targetPort: mqtt
    protocol: TCP
  - name: mqttssl
    port: {{ .Values.service.ports.mqttssl }}
    targetPort: mqttssl
    protocol: TCP
  - name: ws
    port: {{ .Values.service.ports.ws }}
    targetPort: ws
    protocol: TCP
  - name: wss
    port: {{ .Values.service.ports.wss }}
    targetPort: wss
    protocol: TCP
  - name: dashboard
    port: {{ .Values.service.ports.dashboard }}
    targetPort: dashboard
    protocol: TCP
  selector:
    {{- include "emqx.selectorLabels" . | nindent 4 }}